#lang rosette

;;; This is a list of 66 popular drugs that treats a veriety of ailements. 
;;; In reality, a doctor has significantly less than 68 drugs at their disposal since they
;;; can't memorize all the potential interactions. They only know a handful of interactions for 
;;; their domain.
(define drug-names '(
    Acetaminophen
    Adderall
    Amitriptyline
    Amlodipine
    Amoxicillin
    Ativan
    Atorvastatin
    Azithromycin
    Benzonatate
    Brilinta
    Bunavail
    Buprenorphine
    Cephalexin
    Ciprofloxacin
    Citalopram
    Clindamycin
    Clonazepam
    Cyclobenzaprine
    Cymbalta
    Doxycycline
    Dupixent
    Entresto
    Entyvio
    Farxiga
    Fentanyl
    Gabapentin
    Gilenya
    Humira
    Hydrochlorothiazide
    Hydroxychloroquine
    Ibuprofen
    Imbruvica
    Invokana
    Januvia
    Jardiance
    Kevzara
    Lexapro
    Lisinopril
    Lofexidine
    Loratadine
    Lyrica
    Melatonin
    Meloxicam
    Metformin
    Methadone
    Methotrexate
    Metoprolol
    Naloxone
    Naltrexone
    Naproxen
    Omeprazole
    Onpattro
    Otezla
    Ozempic
    Pantoprazole
    Prednisone
    Probuphine
    Rybelsus
    secukinumab
    Sublocade
    Tramadol
    Trazodone
    Viagra
    Wellbutrin
    Xanax
    Zubsolv
    )) 

;;; This is a list of 53 'popular' ailements.
;;; If this is not enough, there is a way longer list at https://www.nhsinform.scot/illnesses-and-conditions/a-to-z
(define ailements '(
    Acne
    ADHD
    HIV
    Allergies
    Alzheimer
    Angina
    Anxiety
    Arthritis
    Asthma
    Bipolar-Disorder
    Bronchitis
    Cancer
    Cholesterol
    Colds
    Fever
    Flu
    Constipation
    COPD
    Covid-19
    Depression
    Diabetes-Type-1
    Diabetes-Type-2
    Diarrhea
    Eczema
    Erectile Dysfunction
    Fibromyalgia
    Gastrointestinal
    Gastroesophageal-Reflux-Disease
    Gout
    Hair-Loss
    Hayfever
    Heart-Disease
    Herpes
    Hypertension
    Hypothyroidism
    Headache
    Irritable-Bowel
    Incontinence
    Insomnia
    Menopause
    Migraine
    Osteoarthritis
    Osteoporosis
    Overweight
    Pain
    Pneumonia
    Psoriasis
    Rheumatoid-Arthritis
    Schizophrenia
    Seizures
    Stroke
    Swine-Flu
    UTI
    ))

(define side-effects '(
    Alopecia
    Arythimia
    Cancer
    Constipation
    Dermatitis
    Diarrhea
    Dizziness
    Drowsiness
    Dry-mouth
    Fever
    Headache
    Insomnia
    Internal-bleeding
    Nausea
    Suicidal-thoughts
    Fatigue
    Muscle-stiffness
    Joint-stiffness

    ))

;;; A list of 142 property of drugs (!)
;;; The list was compiled from https://www.drugs.com/drug-classes.html, I removed some of them
;;; to avoid duplicates and uninteresting entries.
(define drug-properties '(
    5-alpha-reductase-inhibitor
    ACE-inhibitors
    adamantane-antiviral
    adrenal-cortical-steroid
    adrenergic-bronchodilator
    alkylating-agent
    allergenic
    alpha-glucosidase-inhibitor
    amebicide
    aminoglycoside
    aminopenicillin
    aminosalicylate
    analgesic
    angiotensin-receptor-blocker
    anorexiant
    sedative
    hypnotic
    aromatase-inhibitor
    bacterial vaccines
    barbiturate
    benzodiazepine
    beta-blocker
    biological
    bisphosphonate
    bronchodilator
    BTK-inhibitor
    calcimimetic
    calcineurin-inhibitor
    calcitonin
    calcium-channel-blocking-agent
    carbamate-anticonvulsant
    carbapenem
    carbonic-anhydrase-inhibitor
    cardiac-stressing-agent
    cardioselective-beta-blocker
    cardiovascular-agent
    catecholamine
    CD20-monoclonal-antibody
    CD30-monoclonal-antibody
    CD33-monoclonal-antibody
    CD38-monoclonal-antibody
    CD52-monoclonal-antibody
    cephalosporin
    cerumenolytic
    CGRP-inhibitor
    chelating-agent
    chloride-channel-activator
    cholesterol-absorption-inhibitor
    cholinergic-muscle-stimulant
    cholinesterase-inhibitor
    CNS-stimulant
    coagulation-modifier
    contraceptive
    corticotropin
    cox-2-inhibitor
    decongestant
    digestive-enzyme
    diuretic
    echinocandins
    EGFR-inhibitor
    estrogen
    expectorant
    gastrointestinal-agent
    general-anesthetic
    glucocorticoid
    glycylcycline
    growth-hormone
    H2-antagonist
    hedgehog-pathway-inhibitor
    heparin
    HER2-inhibitor
    hydantoin-anticonvulsants
    immunostimulant
    immunosuppressant
    inotropic
    insulin
    interleukin
    intravenous
    ketolide
    laxative
    leprostatic
    macrolide
    meglitinide
    metabolic
    methylxanthine
    mineralocorticoid
    mitotic inhibitor
    mouth-and-throat-product
    mTOR-inhibitor
    mucolytics
    multikinase inhibitors
    muscle relaxants
    mydriatics
    narcotic
    NHE3-inhibitor
    NS5A-inhibitors
    nutritional-product
    ophthalmic-anesthetic
    ophthalmic-anti-infective
    ophthalmic-anti-inflammatory
    ophthalmic-glaucoma
    ophthalmic-steroid
    oxazolidinone
    PARP-inhibitor
    PCSK9-inhibitor
    penicillin
    phenothiazine-antiemetic
    phenothiazine-antipsychotic
    PI3K-inhibitor
    plasma-expander
    probiotic
    psychotherapeutic
    psychotherapeutic 
    quinolone
    radiocontrast-agent
    renin-inhibitor
    respiratory-agent
    salicylate
    sclerosing-agent
    SGLT-2 inhibitor
    muscle-relaxant
    spermicide
    statin
    sulfonamide
    sulfonylurea
    tetracyclic-antidepressant
    thiazide-diuretic
    thrombolytic
    thyroid-drug
    tocolytic-agent
    topical-agent
    vasodilator
    vasopressor
    VEGF/VEGFR-inhibitor
    vitamin
    VMAT2-inhibitor
))